CREATE TABLE BASE_PRICE (
	BP_ID INT NOT NULL,
	Size VARCHAR(45) NOT NULL,
	Crust VARCHAR(45) NOT NULL,
	Price DECIMAL(10,2) NOT NULL,
	Base_Cost DECIMAL(10,2) NOT NULL,
	PRIMARY KEY (BP_ID)
	);

CREATE TABLE ORDERS (
	OrderNum INT NOT NULL,
	PRIMARY KEY (OrderNum)
	);

CREATE TABLE PIZZA (
	P_ID INT NOT NULL,
	Pprice DECIMAL(10,2) NOT NULL,
	Cost DECIMAL(10,2) NOT NULL,
	Status VARCHAR(45) NOT NULL,
	timestamp TIMESTAMP NOT NULL,
	BP_ID INT NOT NULL,
        OrderNum INT NOT NULL,
	PRIMARY KEY (P_ID),
	FOREIGN KEY (BP_ID) REFERENCES BASE_PRICE (BP_ID),
	FOREIGN KEY (OrderNum) REFERENCES ORDERS (OrderNum)
	);

CREATE TABLE TOPPING (
	Tname VARCHAR(45) NOT NULL,
	CustPrice DECIMAL(10,2) NOT NULL,
	BusPrice DECIMAL(10,2) NOT NULL,
	Inventory DECIMAL(10,2),
	Sm_Top DECIMAL(10,2),
	Md_Top DECIMAL(10,2),
	Lg_Top DECIMAL(10,2),
	XL_Top DECIMAL(10,2),
	PRIMARY KEY (Tname)
	);

CREATE TABLE DISCOUNT (
	Disc_ID INT NOT NULL,
	Dname VARCHAR(45) NOT NULL,
	Disc_Type VARCHAR(45) NOT NULL,
	Amount FLOAT NOT NULL,
	PRIMARY KEY (Disc_ID)
	);
CREATE TABLE CUSTOMER (
	Cust_ID INT NOT NULL,
	Cname VARCHAR(45) NOT NULL,
	Phone VARCHAR(45) NOT NULL,
	Address VARCHAR(45),
	PRIMARY KEY (Cust_ID)
	);

CREATE TABLE DINE_IN (
	OrderNum INT NOT NULL,
	TableNum INT NOT NULL,
	PRIMARY KEY (OrderNum),
	FOREIGN KEY (OrderNum)REFERENCES ORDERS (OrderNum)
	);

CREATE TABLE PICKUP (
	OrderNum INT NOT NULL,
	Cust_ID INT NOT NULL,
	PRIMARY KEY (OrderNum),
	FOREIGN KEY (OrderNum) REFERENCES ORDERS (OrderNum),
	FOREIGN KEY (Cust_ID) REFERENCES CUSTOMER (Cust_ID)
	);

CREATE TABLE DELIVERY (
	OrderNum INT NOT NULL,
	Cust_ID INT NOT NULL,
	PRIMARY KEY (OrderNum),
	FOREIGN KEY (OrderNum) REFERENCES ORDERS (OrderNum),
	FOREIGN KEY (Cust_ID) REFERENCES CUSTOMER (Cust_ID)
	);

CREATE TABLE HAS (
	P_ID INT NOT NULL,
	Tname VARCHAR(45) NOT NULL,
	Dbl_Top BOOLEAN,
	PRIMARY KEY (P_ID, Tname),
	FOREIGN KEY (P_ID) REFERENCES PIZZA (P_ID),
	FOREIGN KEY (Tname) REFERENCES TOPPING (Tname)
	);

CREATE TABLE DISC_APPLIED_TO_PIZZA (
	P_ID INT NOT NULL,
	Disc_ID INT NOT NULL,
	PRIMARY KEY (P_ID, Disc_ID),
	FOREIGN KEY (P_ID) REFERENCES PIZZA (P_ID),
	FOREIGN KEY (Disc_ID) REFERENCES DISCOUNT (Disc_ID)
	);

CREATE TABLE DISC_APPLIED_TO_OR (
	OrderNum INT NOT NULL,
	Disc_ID INT NOT NULL,
	PRIMARY KEY (OrderNum, Disc_ID),
	FOREIGN KEY (OrderNum) REFERENCES ORDERS (OrderNum),
	FOREIGN KEY (Disc_ID) REFERENCES DISCOUNT (Disc_ID)
	);

CREATE TABLE SEATNUM (
	DineNum INT NOT NULL,
	SeatNum INT NOT NULL,
	PRIMARY KEY (DineNum, SeatNum),
	FOREIGN KEY (DineNum) REFERENCES DINE_IN (OrderNum)
	);

