DROP TABLE  IF EXISTS SEATNUM;

DROP TABLE  IF EXISTS DISC_APPLIED_TO_OR;

DROP TABLE  IF EXISTS DISC_APPLIED_TO_PIZZA;

DROP TABLE  IF EXISTS HAS;

DROP TABLE  IF EXISTS DELIVERY;

DROP TABLE  IF EXISTS PICKUP;

DROP TABLE  IF EXISTS DINE_IN;

DROP TABLE  IF EXISTS CUSTOMER;

DROP TABLE  IF EXISTS DISCOUNT;

DROP TABLE  IF EXISTS TOPPING;

DROP TABLE  IF EXISTS PIZZA;

DROP TABLE  IF EXISTS ORDERS;

DROP TABLE IF EXISTS BASE_PRICE;
